version: '3'
services:
  api1:
    image: dashboardinfo/api1
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
        JWT_SECRET: "${JWT_SECRET}"
        NODE_ENV: "production"
        WAIT_HOSTS: db:27017
        WAIT_HOSTS_TIMEOUT: 60
    volumes:
        - ../certs:/apps/api1/certs
  db:
      image: mongo:latest
      volumes:
        - ./mongoDataProd:/data/db
      ports:
        - "27017"
