name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
        image: dashboardinfo/api1
        tag: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
